[package]
name = "my_library"
version = "0.1.0"
authors = ["BuRny <gamingburny@gmail.com>"]
edition = "2018"

[lib]
name = "my_library"
crate-type = ["cdylib"]

[dependencies.pyo3]
pyo3 = "0.8.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]